// Little Mandarin Club — Vocabulary Data
const VOCABULARY = {
  categories: [
    {
      id: "animals",
      name: "Animals 动物",
      icon: "🐾",
      color: "#FF6F61",
      words: [
        { chinese: "猫", pinyin: "māo", english: "Cat", emoji: "🐱" },
        { chinese: "狗", pinyin: "gǒu", english: "Dog", emoji: "🐶" },
        { chinese: "鱼", pinyin: "yú", english: "Fish", emoji: "🐟" },
        { chinese: "鸟", pinyin: "niǎo", english: "Bird", emoji: "🐦" },
        { chinese: "熊猫", pinyin: "xióng māo", english: "Panda", emoji: "🐼" },
        { chinese: "兔子", pinyin: "tù zi", english: "Rabbit", emoji: "🐰" },
      ],
    },
    {
      id: "food",
      name: "Food 食物",
      icon: "🍜",
      color: "#FFD93D",
      words: [
        { chinese: "苹果", pinyin: "píng guǒ", english: "Apple", emoji: "🍎" },
        { chinese: "香蕉", pinyin: "xiāng jiāo", english: "Banana", emoji: "🍌" },
        { chinese: "米饭", pinyin: "mǐ fàn", english: "Rice", emoji: "🍚" },
        { chinese: "面条", pinyin: "miàn tiáo", english: "Noodles", emoji: "🍜" },
        { chinese: "水", pinyin: "shuǐ", english: "Water", emoji: "💧" },
        { chinese: "牛奶", pinyin: "niú nǎi", english: "Milk", emoji: "🥛" },
      ],
    },
    {
      id: "colors",
      name: "Colors 颜色",
      icon: "🎨",
      color: "#8D4BF6",
      words: [
        { chinese: "红色", pinyin: "hóng sè", english: "Red", emoji: "🔴" },
        { chinese: "蓝色", pinyin: "lán sè", english: "Blue", emoji: "🔵" },
        { chinese: "绿色", pinyin: "lǜ sè", english: "Green", emoji: "🟢" },
        { chinese: "黄色", pinyin: "huáng sè", english: "Yellow", emoji: "🟡" },
        { chinese: "粉色", pinyin: "fěn sè", english: "Pink", emoji: "🩷" },
        { chinese: "紫色", pinyin: "zǐ sè", english: "Purple", emoji: "🟣" },
      ],
    },
    {
      id: "numbers",
      name: "Numbers 数字",
      icon: "🔢",
      color: "#6BCB77",
      words: [
        { chinese: "一", pinyin: "yī", english: "One", emoji: "1️⃣" },
        { chinese: "二", pinyin: "èr", english: "Two", emoji: "2️⃣" },
        { chinese: "三", pinyin: "sān", english: "Three", emoji: "3️⃣" },
        { chinese: "四", pinyin: "sì", english: "Four", emoji: "4️⃣" },
        { chinese: "五", pinyin: "wǔ", english: "Five", emoji: "5️⃣" },
        { chinese: "十", pinyin: "shí", english: "Ten", emoji: "🔟" },
      ],
    },
    {
      id: "greetings",
      name: "Greetings 问候",
      icon: "👋",
      color: "#4D96FF",
      words: [
        { chinese: "你好", pinyin: "nǐ hǎo", english: "Hello", emoji: "👋" },
        { chinese: "谢谢", pinyin: "xiè xiè", english: "Thank you", emoji: "🙏" },
        { chinese: "再见", pinyin: "zài jiàn", english: "Goodbye", emoji: "✌️" },
        { chinese: "对不起", pinyin: "duì bù qǐ", english: "Sorry", emoji: "😔" },
        { chinese: "早上好", pinyin: "zǎo shàng hǎo", english: "Good morning", emoji: "🌅" },
        { chinese: "晚安", pinyin: "wǎn ān", english: "Good night", emoji: "🌙" },
      ],
    },
    {
      id: "family",
      name: "Family 家人",
      icon: "👨‍👩‍👧",
      color: "#FF9A3C",
      words: [
        { chinese: "妈妈", pinyin: "mā ma", english: "Mum", emoji: "👩" },
        { chinese: "爸爸", pinyin: "bà ba", english: "Dad", emoji: "👨" },
        { chinese: "哥哥", pinyin: "gē ge", english: "Big brother", emoji: "👦" },
        { chinese: "姐姐", pinyin: "jiě jie", english: "Big sister", emoji: "👧" },
        { chinese: "爷爷", pinyin: "yé ye", english: "Grandpa", emoji: "👴" },
        { chinese: "奶奶", pinyin: "nǎi nai", english: "Grandma", emoji: "👵" },
      ],
    },
  ],
};
